(copy_files ../../vendor/owebview/lib/webview_stubs.cpp)

(rule
 (target webview_stubs.o)
 (deps
  webview_stubs.cpp
  %{workspace_root}/vendor/owebview/vendor/webview.h
  %{workspace_root}/vendor/webview2-sdk-1.0.1150.38/include/WebView2.h)
 (action
  (run
   x86_64-w64-mingw32-g++
   -std=c++14
   -I %{ocaml-config:standard_library}
   -I ../../vendor/owebview/vendor
   -I ../../vendor/webview2-sdk-1.0.1150.38/include
   -c %{dep:webview_stubs.cpp}
   -o %{target})))

(rule
 (target thread_probe_stubs.o)
 (deps thread_probe_stubs.cpp)
 (action
  (run
   x86_64-w64-mingw32-g++
   -std=c++14
   -I %{ocaml-config:standard_library}
   -c %{dep:thread_probe_stubs.cpp}
   -o %{target})))

(executable
 (name main)
 (libraries unix threads)
 (extra_objects webview_stubs thread_probe_stubs)
 (link_flags
  (:standard
   -cclib -lstdc++
   -cclib -ladvapi32
   -cclib -lole32
   -cclib -lshell32
   -cclib -lshlwapi
   -cclib -luser32
   -cclib -lversion)))