(executable
 (name discover)
 (modules discover)
 (libraries unix))

(rule
 (targets c_flags.sexp c_library_flags.sexp)
 (action (run %{exe:discover.exe})))

(library
 (name webui_raw)
 (public_name ocaml-webui.raw)
 (wrapped false)
 (modules webui_raw webui_raw_native webui_raw_state)
 (foreign_stubs
  (language cxx)
  (names webui_raw_stubs)
  (extra_deps
   (glob_files_rec ../../vendor/webview/core/include/*)
   (glob_files_rec ../../vendor/webview/compatibility/mingw/include/*)
   (glob_files_rec ../../vendor/webview2-sdk-1.0.1150.38/include/*))
  (flags
   (:standard
    (:include c_flags.sexp))))
 (c_library_flags
  (:include c_library_flags.sexp)))
